# -*- coding: utf-8 -*-
"""201810912김연출_실습3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1596YHQ6TL2l6TdAg0bFD6kOiPlzwp-ls
"""

#실습문제 1
print("덧셈을 하고 싶은 양의 정수들을 입력하세요. 0 입력 시 종료")
sum = 0 
num = -1
while(True):
  num = int(input(''))
  if(num == 0):
    break
  sum +=num
print("총 합은 ",sum,"입니다")

#실습문제 2
num = int(input('자연수 입력:'))
i = 1
sum = 0
while(i<= num):
  if(i%2==0):
    sum += i
  i+=1
print("짝수 합:",sum)

#실습문제 3
num = int(input('정수를 입력하세요:'))
i = 1
fact = 1
while(i<= num):
  fact *= i
  i+=1
print(num,"! =",fact)

#실습문제 4
string = input('문자열을 입력하세요:')
i = len(string)
while(i>0):
  print(string[i-1],end='')
  i-=1

#실습문제 5-1
decimal = int(input('10진수를 입력하세요'))
result = 1
while(decimal>=1):
  remain = decimal%2
  decimal /= 2
  result = int(result*10 + remain)
result = int(result/10)
print(result,"(2)",sep="")

#실습문제 5-1 다른 풀이
decimal = int(input('10진수를 입력하세요'))
mystr=""
if(decimal==0):
  mystr = "0"
else:
  while(decimal >=1):
    remain = int(decimal%2)
    decimal/=2
    mystr = str(remain)+mystr
print(mystr,"(2)",sep="")

#실습문제 6
string = input('문자열 입력:')

i = 0
k = len(string)-1
outloop = 0

while(i<len(string)-1):
 
 if(string[i]!=string[k]):
   outloop = -1
 i=i+1
 k=k-1
 if(outloop == -1):
  break
if(outloop==-1):
  print("회문이 아닙니다")
else:
  print("회문입니다")