# -*- coding: utf-8 -*-
"""201810912김연출_과제4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15sLbrv6aeflTBorrGHkRE7lYIco6x3Ya
"""

#실습문제 4
string = input('문자열을 입력하세요:')
i = len(string)
while(i>0):
  print(string[i-1],end='')
  i-=1

#실습문제 5-2
str1 = input('2진수를 입력하세요: ')
sum = 0
for i in range(len(str1)-1,-1,-1):
  sum += int(str1[i])*(2**(len(str1)-1-i))
 
print(sum)

#실습문제 6
string = input('문자열 입력:')

i = 0
k = len(string)-1
outloop = 0

while(i<len(string)-1):
 
 if(string[i]!=string[k]):
   outloop = -1
 i=i+1
 k=k-1
 if(outloop == -1):
  break
if(outloop==-1):
  print("회문이 아닙니다")
else:
  print("회문입니다")

#실습문제 1번
num = int(input('자연수 입력:'))
sum = 0
for i in range(1,num+1):
  if(i%2==0):
    sum+=i
print(sum)

#실습문제 2번
num = int(input('정수를 입력하세요'))
fac = 1
for i in range(1,num+1):
  fac*=i
print(fac)

#실습문제 3번
str1 = input('문자열을 입력:')

print("뒤집어서 출력:", end =" ")
for i in range(len(str1)-1,-1,-1):
  print(str1[i],end='')

str1 = input('문자열을 입력하세요')
out = -1
for i in range(0,len(str1)//2):
  if(str1[i]!=str1[len(str1)-1-i]):
    out=0
    break
  
if(out==0):
  print("회문이아닙니다")
else:
  print("회문입니다")

str1 = input("소문자 문자열을 입력하세요: ")
for i in range(0,len(str1)):
  print(chr(ord(str1[i])-32),end="")