# -*- coding: utf-8 -*-
"""201810912김연출.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/119IvYJPsGrO47R0iyo7Eyg4zEo8lyKov
"""

#1번문제
print("Input (x1,y1), (x2,y2)")
x1 = int(input('x1:'))
y1 = int(input('y1:'))
x2 = int(input('x2:'))
y2 = int(input('y2:'))
result = ((((x1-x2)**2+(y1-y2)**2)**(1/2))**2)/2

print('area:',result)

#2번문제
x = int(input('input x:'))
print('@'*x)

#3번문제
last_name = input('Input the last name:')
first_name = input('Inpt the first name:')
fullname = last_name+first_name
print(fullname)

#4번문제
inch = int(input('Input inch:'))
cm = float(inch*2.54)
print(inch,"inch ->",cm,"cm")

#5번문제
x = "KIM"
print(bin(ord(x[0])),end=" ")
print(bin(ord(x[1])),end=" ")
print(bin(ord(x[2])))