# -*- coding: utf-8 -*-
"""201810912김연출_실습9주차.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZOXk6FHmkfYRQ4HYZDqOELlr3KR2aqB_
"""

def myFunc(x) :
  print("순서1 ")
  result = x**2 + 5*x +3
  return result

print("순서2 ")
x = 10
y = myFunc(x)
print("순서 3")
print("f(%d) = %d"%(x,y))

#실습문제 1
def addnum(num1,num2):
  result = num1+num2
  return result

print(addnum(3,5))

#실습문제 2

def costForCity(str1):
  if(str1 =="춘천"):
    cost = 5000
  elif(str1=="부산"):
    cost = 30000
  elif(str1 == "대구"):
    cost = 2000
  elif(str1 == "수원"):
    cost = 10000
  else:
    print("잘못입력했어요")
  
  return cost

instr = input('목적지를 입력하세요:')
print("%s까지의 금액은 %d원입니다"%(instr,costForCity(instr)))

#실습문제 3
def baseExponent(x,y):
  result = 1
  for i in range(0,y):
    result *= x
  return result

innum1 = int(input('밑수를 입력하세요: '))
innum2 = int(input('지수를 입력하세요: '))
print("거듭제곱값 : %d"%baseExponent(innum1,innum2))

#실습문제 4
def is_prime(num):
  p_count = 0
  for i in range(1,num+1):
    if(num%i==0):
      p_count += 1
  if(p_count==2):
    print("소수입니다.")
  else:
    print("소수가 아닙니다.")

innum = int(input('양의 정수 입력: '))
is_prime(innum)

#실습문제 5
def plus(num1,num2):
  result = num1+ num2
  return result

def minus(num1,num2):
  if(num1>=num2):
    result = num1-num2
  else:
    result = num2 - num1
  return result

def mul(num1,num2):
  result = num1*num2
  return result

def div(num1,num2):
  if(num2==0):
    return 0
  else:
    result = num1 / num2
    return result

def calculrator():
  while(1):
    print("*** 계산기 ***")
    numx = int(input("1. 덧셈 2.뺄셈 3.곱셈 4.나눗셈 5.종료"))

    if(numx==5):
      break

    print("정수 2개 입력:")
    num1 = float(input())
    num2 = float(input())

    if(numx==1):
      print("결과 : %f"%(plus(num1,num2)))
    elif(numx==2):
      print("결과 : %f"%(minus(num1,num2)))
    elif(numx==3):
      print("결과 : %f"%(mul(num1,num2)))
    elif(numx==4):
      print("결과 : %f"%(div(num1,num2)))
    else:
      print("다시 선택해주세요")

calculrator()