# -*- coding: utf-8 -*-
"""201810912_김연출_실습_10주차

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t1yCSD7ZSAMPOF-MUBRZzYBSPGw3QvDT
"""

#실습문제 1
list_fruit = []
print("=== 좋아하는 과일 등록 프로그램 ===\n0을 입력하면 입력 종료")
while True:
  fruit = input("과일명 입력: ")
  if(fruit=="0"):
    break
  list_fruit.append(fruit)
print("당신이 좋아하는 과일들: %s"%list_fruit)

#실습문제 2
print("친구이름 등록 프로그램\n0을 입력하면 입력 종료")
list_friends = []
while True:
  friends = input("친구 이름 입력")
  if(friends=="0"):
    break
  list_friends.append(friends)
print("등록 완료")
print("입력된 순서: ",list_friends)
list_friends = sorted(list_friends)
print("정렬된 순서: ",list_friends)

#실습문제 3
list_stu = list()
for i in range(0,5):
  x = int(input("%d번 학생 성적 입력:"%(i+1)))
  list_stu.append(x)

i=1
sum = 0
for score in list_stu:
  print("%d번 학생 성적: %d"%(i,score))
  i+=1
  sum+=score
print("성적 합계:%5d점"%sum)
print("성적 평균:%5d점"%(sum/5))

#실습문제 4 
list_score = []
sum_kor = 0
sum_eng =0
sum_math = 0

for i in range(1,4):
  kor = int(input("국어점수 입력:"))
  eng = int(input("영어점수 입력:"))
  math = int(input("수학점수 입력:"))
  sum_kor += kor
  sum_eng += eng
  sum_math += math
  list_score.append([i,kor,eng,math])

print("번호\t국어\t영어\t수학")
print("-"*30)

for i in list_score:
  for j in i:
    print(j,end="\t")
  print("")
1
print("-"*30)
print("평균\t%.1f\t%.1f\t%.1f"%(sum_kor/3,sum_eng/3,sum_math/3))

#실습문제 5
num = (10,20,30,40,50,60,70,80,90,100)
for i in num:
  print(i)