# -*- coding: utf-8 -*-
"""201810912김연출_과제2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vet3GJjQfFVmXAwQ09MJme-wfkrKQjHI

실습문제 1_1
"""

score = int(input("현재 이수 학점을 입력하세요:"))
if(score>=140) :
  print("졸업이 가능합니다.")
else:
  print("졸업이 불가능합니다.")

"""실습문제 1_2"""

print("19세 미만, 키가 140 초과이면 탑승가능")
age = int(input("나이를 입력하세요:"))
height = int(input("키를 입력하세요:"))
if (age < 19) and (height > 140):
  print("탑승 가능합니다")
else:
  print("탑승 불가능합니다")

"""실습문제 1_3"""

apple = int(input("구매한 사과 개수:"))
grape = int(input("구매한 포도 개수:"))
pear = int(input("구매한 배 개수:"))
mandarin = int(input("구매한 귤 개수:"))
sum = apple*1000+grape*3000+pear*2000+mandarin*500
if(grape >= 3 ):
 sum = int(sum*0.9)
 print("10% 할인되었습니다")
print("총 금액:",sum)

"""실습문제 1_4"""

bank_name = input("은행 이름:")
way = input("방법:")
check_money = input("돈_수표:")
if(bank_name == '파이') and ((way == 'card') or (way =='bankbook')) and (check_money == 'money'):
  print("입금 가능합니다")
else :
  print("입금 불가능합니다")

"""실습문제 2_1"""

finger_size = float(input("손가락 둘레를 입력하세요:"))
ring_size = 0
if(finger_size>51 and finger_size <=52):
  print("9")
elif(finger_size>52 and finger_size<=53):
  print("10")
elif(finger_size>53 and finger_size <=54):
  print("11")
elif(finger_size>54 and finger_size <=55):
  print("12")
else:
  print("반지 제작 불가능")

"""실습문제 2_2"""

calcul = int(input("1.덧셈 2.뺄셈 3.곱셈 4.나눗셈: "))
num1 = int(input("양의 정수 첫번째 입력:"))
num2 = int(input("양의 정수 두번째 입력:"))
if calcul==1:
  print(num1+num2)
elif calcul==2:
  print(num1-num2)
elif calcul==3:
  print(num1*num2)
elif calcul==4:
  print(num1/num2)
else:
  print("각 연산에 배정된 숫자만 입력이 가능합니다.")

"""실습문제 2_3"""

num1 = int(input("첫번째 양의 정수: "))
num2 = int(input("두번째 양의 정수: "))
num3 = int(input("세번째 양의 정수: "))
max = num1
if(max<num2):
  max=num2
if(max<num3):
  max=num3
print(max)

"""실습문제 2_4"""

num1 = int(input("첫번째 양의 정수: "))
num2 = int(input("두번째 양의 정수: "))
num3 = int(input("세번째 양의 정수: "))
sum = num1+num2+num3

max = num1
if(max<num2):
  max=num2
if(max<num3):
  max=num3

if(sum%2==0):
  print(max)
else:
  print(sum)

"""실습문제 2_5"""

leg1 = int(input("첫번째 변 입력"))
leg2 = int(input("두번째 변 입력"))
leg3 = int(input("세번째 변 입력"))

max = leg1
if(max<leg2):
  max=leg1
if(max<leg3):
  max=leg3

sum = leg1+leg2+leg3



if(max >= sum-max):
  print("삼각형이 아닙니다")
elif(leg1==leg2 and leg1==leg3):
  print("정삼각형")
elif((leg1==leg2 and leg1!=leg3) or (leg2==leg3 and leg2!=leg1) or (leg1==leg3 and leg1 !=leg2)):
  print("이등변삼각형")
elif(leg1**2+leg2**2+leg3**2-max**2 == max**2):
  print("직각삼각형")
else:
  print("일반삼각형")