# -*- coding: utf-8 -*-
"""201810912김연출_실습5.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OcUHG1nBkJ-t8XLIYz7AtZ5z7wyh755l
"""

a = 2019 / 13
b = 10 / 3

print("%5.2f + %4.2f = %7.2f" % (a,b,(a+b)))
print("%5.2f - %4.2f = %7.2f" % (a,b,(a-b)))
print("%5.2f * %4.2f = %7.2f" % (a,b,(a*b)))
print("%5.2f / %4.2f = %7.2f" % (a,b,(a/b)))

#실습문제 1
print('== 섭씨-화씨 온도변환기==')
c = int(input('섭씨온도 입력->'))
print("섭씨온도:{0:.2f}".format(c))
f = c*(9/5)+32
print("화씨온도:{0:.2f}".format(f))

#실습문제 2
print("=== 원리금 계산 프로그램 ===")
principal = int(input('저축금액 입력:'))
interest = int(principal* 0.0375)
tax = int(interest * 0.15)
result = principal + interest - tax
print("원금:{0:12d}".format(principal))
print("이자:{0:12d}".format(interest))
print("세금:{0:12d}".format(tax))
print("최종:{0:12d}".format(result))

#실습문제 3
num1 = int(input('정수1 입력:'))
num2 = int(input('정수2 입력:'))
add = num1+num2
min = num1 - num2
mul = num1 * num2
div = num1 / num2

print("{0:2d} + {1:2d} = {2:5d}".format(num1,num2,add))
print("{0:2d} - {1:2d} = {2:5d}".format(num1,num2,min))
print("{0:2d} * {1:2d} = {2:5d}".format(num1,num2,mul))
print("{0:2d} + {1:2d} = {2:5.2f}".format(num1,num2,div))

#실습문제 4
num1 = float(input('실수1 입력:'))
num2 = float(input('실수2 입력:'))
add = num1+num2
min = num1 - num2
mul = num1 * num2
div = num1 / num2

print("{0:2.2f} + {1:2.2f} = {2:7.2f}".format(num1,num2,add))
print("{0:2.2f} - {1:2.2f} = {2:7.2f}".format(num1,num2,min))
print("{0:2.2f} * {1:2.2f} = {2:7.2f}".format(num1,num2,mul))
print("{0:2.2f} / {1:2.2f} = {2:7.2f}".format(num1,num2,div))