# -*- coding: utf-8 -*-
"""201810912_김연출_실습_12주차

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/105XWYOUEYZvFI7O2JRJVK1-8WKuuc45u
"""

mydict = {}

fp = open("drive/MyDrive/ColabNotebooks/movie_data.txt","r",encoding='cp949')

for line in fp.readlines():
  line = line.strip()
  x = line.split("|")
  mydict[x[2]] = x
fp.close()

while True :
  in_str = input("영화이름 입력 (종료 0):")

  if in_str == '0' :
    break
  else:
    if in_str in mydict.keys():
      print("Company     : ",mydict[in_str][3])
      print("Release data: ",mydict[in_str][4])
      print("Country     : ",mydict[in_str][5])
      print("Total screen: ",mydict[in_str][6])
      print("Profit      : ",mydict[in_str][7])
      print("Total num   : ",mydict[in_str][8])
      print("Grade       : ",mydict[in_str][9])
    
    else:
      print("데이터베이스에 없는 영화입니다.")

  print("-------------------------------")